### ISSUE TITLE
Error "unsupported operand type(s) for /: 'unicode' and 'int'" when trying to set 'dim' parameter for Earth imagery API search

### ISSUE THREAD

**Issue by sfatfarma** [nasa/api-docs#86]
Hello, I receive the following error when trying to set the 'dim' param to any value for the earth imagery api search.

Query: https://api.nasa.gov/planetary/earth/imagery?lon=100.75&lat=1.5&dim=0.01&cloud_score=True&api_key=DEMO_KEY

Response: 

{"message": "Admins have been notified.", "error": "unsupported operand type(s) for /: 'unicode' and 'int'"}

I tried many combinations for the dim parameter, but none worked. Am I missing something? Thank you!

**Comment by BrunoBiluca** [comment]
Yes this in not working.

**Comment by sfatfarma** [comment]
Any solutions?

**Comment by jnbetancourt** [comment]
The code has been fixed, but we're working on deploying to a different backend. The fix should be live soon, and I'll update this bug when it happens.

**Comment by sfatfarma** [comment]
Thank you very much for your response and for your prompt actions.

Regards,
Szabi.

**Comment by b3m2a1** [comment]
@jnbetancourt I am hitting this issue still. Any idea when the patch will be up?

**Comment by sfatfarma** [comment]
I don't think that the fix made into release, yet. :)

**Comment by jnbetancourt** [comment]
We're currently having deployment issues. I'll update this issue once the fix is deployed. Hopefully it'll be within the next couple weeks.

**Comment by sfatfarma** [comment]
Thank you very much.
